services:
  - type: web
    name: coo-cxo-control-room
    runtime: static
    buildCommand: ""
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
